name = "schlaugh-bot"
main = "build/worker/shim.mjs"
compatibility_date = "2025-05-13"

[build]
command = "cargo install -q worker-build && worker-build --release"


[triggers]
# Every day at 9:10 AM UTC
crons = [ "10 9 * * *" ]


[observability]
enabled = true