name = "schlaugh-bot"
main = "build/worker/shim.mjs"
compatibility_date = "2025-05-13"

[build]
command = "cargo install -q worker-build && worker-build --release"


[triggers]
# Every day at 9:10 AM UTC
crons = ["10 9 * * *"]


[observability]
enabled = true

[vars]
# HACK: wrangler-rs does not support array var, so I wrap it in an object
SCHLAUGH_USERS = { ids = [
    "67c000111610bf329ab41598", # Aelerinya
    "68113e0a798af5591b2971ad", # everchange
    "631ce3e55dbe4e00160430a2", # tutor_vals
] }
